openapi: 3.0.0

info:
  version: 0.0.1
  title: Hex Architecture
  description: Hex Architecture

servers:
  - url: http://localhost:8080/
    description: API location

tags:
  - name: "user"


paths:
  /user/{id}:
    parameters:
      - name: id
        description: id of the user
        schema:
          type: integer
          format: int64
        in: path
        required: true
    get:
      summary: Returns user for a specified id.
      tags:
        - "user"
      description: Returns user for a specified id.
      operationId: getUserById
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        "400":
          description: BAD REQUEST
        "401":
          description: UNAUTH


components:

  schemas:
    UserDTO:
      description: This is the user dto model
      type: object
      properties:
        username:
          type: string
        id:
          type: integer
          format: int64
        wallets:
          type: array
          items:
            $ref: '#/components/schemas/WalletDTO'
    WalletDTO:
      description: This is the wallet dto model
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        balance:
          type: number